version: '3'
services:

  eureka:
    image: discovery-server
    container_name: discovery-server
    build:
      context: ./backend/discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8440:8440"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  agent:
    image: agent-service
    container_name: agent-service
    build:
      context: ./backend/MegaTravelAgent
      dockerfile: Dockerfile
    ports:
      - "8445"
    depends_on:
      - eureka
    links:
      - eureka:eureka
      
  accommodation:
    image: accommodation-service
    container_name: accommodation-service
    build:
      context: ./backend/accommodation-service
      dockerfile: Dockerfile
    ports:
      - "8442"
    depends_on:
      - eureka
    links:
      - eureka:eureka
   
  reservation:
    image: reservation-service
    container_name: reservation-service
    build:
      context: ./backend/reservation-service
      dockerfile: Dockerfile
    ports:
      - "8443"
    depends_on:
      - eureka
    links:
      - eureka:eureka
      
  auth:
    image: auth-service
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "8441"
    depends_on:
      - eureka
    links:
      - eureka:eureka
