//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 10:45:01 PM CEST 
//


package com.xml.MegaTravelMBA.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reservationID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="reservationActive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reservationID",
    "reservationActive"
})
@XmlRootElement(name = "ReservationRequest")
public class ReservationRequest {

    protected long reservationID;
    protected boolean reservationActive;

    /**
     * Gets the value of the reservationID property.
     * 
     */
    public long getReservationID() {
        return reservationID;
    }

    /**
     * Sets the value of the reservationID property.
     * 
     */
    public void setReservationID(long value) {
        this.reservationID = value;
    }

    /**
     * Gets the value of the reservationActive property.
     * 
     */
    public boolean isReservationActive() {
        return reservationActive;
    }

    /**
     * Sets the value of the reservationActive property.
     * 
     */
    public void setReservationActive(boolean value) {
        this.reservationActive = value;
    }

}
