//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.11 at 01:30:41 PM CEST 
//


package model.reservation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.reservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.reservation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link AccommodationUnit.Amenities }
     * 
     */
    public AccommodationUnit.Amenities createAccommodationUnitAmenities() {
        return new AccommodationUnit.Amenities();
    }

    /**
     * Create an instance of {@link AccommodationUnit.PricePlan }
     * 
     */
    public AccommodationUnit.PricePlan createAccommodationUnitPricePlan() {
        return new AccommodationUnit.PricePlan();
    }

    /**
     * Create an instance of {@link AccommodationUnit.Images }
     * 
     */
    public AccommodationUnit.Images createAccommodationUnitImages() {
        return new AccommodationUnit.Images();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Amenity }
     * 
     */
    public Amenity createAmenity() {
        return new Amenity();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link SpecificPrice }
     * 
     */
    public SpecificPrice createSpecificPrice() {
        return new SpecificPrice();
    }

    /**
     * Create an instance of {@link Rating.Comment }
     * 
     */
    public Rating.Comment createRatingComment() {
        return new Rating.Comment();
    }

}
